baseurl = "/"
languageCode = "en-us"
title = "CSSS Seminar Series"
theme = "csss"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    seminars = "/:year/:month/:day/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/UWCSSS"

[params]
    description = "CSSS Seminar Series"
