baseurl = "/"
languageCode = "en-us"
title = "CSSS Seminar Series"
theme = "csss"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    seminars = "/seminars/:year/:month/:day/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/UWCSSS"

[params]
    description = "CSSS Seminar Series"
    currentQuarter = "Fall 2017"
    startTime = "12:30 PM"
    endTime = "1:30 PM"
    location = "Savery 409"
    locationURL = ""
