baseurl = "/"
languageCode = "en-us"
title = "CSSS Seminar Series"
theme = "csss"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
    seminars = "/seminars/:year/:month/:day/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/UWCSSS"

[params]
    description = "CSSS Seminar Series"
    startTime = "12:30 PM"
    endTime = "1:30 PM"
    location = "Savery Hall 409"
    locationURL = "https://www.washington.edu/maps/#!/sav"
    directorName = "Jeffrey Arnold"
    directorEmail = "jrnold@uw.edu"
    currentQuarter = "Fall 2017"
